version: "1"
services:
- type: web
  name: crypto-alert-pro-bot
  runtime: python
  repo: https://github.com/IceReign-MEXT/IceGods-TelegramBot
  plan: free
  envVars:
  - key: TELEGRAM_BOT_TOKEN
    sync: false
  - key: TELEGRAM_CHANNEL_ID
    sync: false
  - key: OPENAI_API_KEY
    sync: false
  - key: INFURA_API_KEY
    sync: false
  - key: INFURA_API_SECRET
    sync: false
  - key: ETH_WALLET
    sync: false
  - key: SOL_WALLET
    sync: false
  - key: DATABASE_PATH
    value: "bot.db"
  - key: PORT
    value: "5000"
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn -b 0.0.0.0:5000 wsgi:app
  healthCheckPath: /healthz